### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by RybazPolski** [PolishCloneTroopers/project-convor#11]

**Comment by PolishCloneTroopers** [comment]
Struggling to host it for free.99 :')

**Comment by RybazPolski** [comment]
Struggling to host it for FREE.99 :')

**Comment by PolishCloneTroopers** [comment]
Well there are a lot, lot problems in making this service for free...

**Comment by RybazPolski** [comment]
Well there are a lot, lot problems in making this service for free...

**Comment by RybazPolski** [comment]
Database deployed on Postgre along with the #14 in which I migrated API to Vercel hosting.
